In [1]:
# varify directories and configurations availibility

import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")

PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "data"
AUDIO_OUTPUT_DIR = DATA_DIR / "input" / "audio"
SAMPLE_DATA_DIR = DATA_DIR / "sample_data"

AUDIO_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
SAMPLE_DATA_DIR.mkdir(parents=True, exist_ok=True)

client = OpenAI(api_key=OPENAI_API_KEY)

print(f"Project Root        : {PROJECT_ROOT}")
print(f"Audio Directory     : {AUDIO_OUTPUT_DIR}")
print(f"Sample Data Dir     : {SAMPLE_DATA_DIR}")

Project Root        : d:\LearnPython\multi-model-capability-project
Audio Directory     : d:\LearnPython\multi-model-capability-project\data\input\audio
Sample Data Dir     : d:\LearnPython\multi-model-capability-project\data\sample_data

In [2]:
# prompt and scenarios for audio generation
TRANSCRIPT_PROMPT = """
You are an expert customer support conversation simulator.

Generate a realistic conversation between a customer and customer support agent.

Scenario: {scenario}

Requirements:
- Conversation duration should be approximately 1-2 minutes when spoken aloud.
- Include natural greetings and a professional closing.
- The customer should clearly explain their issue.
- The support agent should ask relevant questions.
- The support agent should provide an appropriate resolution whenever possible.
- Make the conversation realistic, random sentiment, and conversational.
- Do NOT include speaker timestamps.
- Prefix each utterance with either "Customer:" or "Agent:".
- Return ONLY the conversation transcript.
"""

SCENARIOS =[
    "Billing Issue",
    "Product Technical Support",
    "Product Inquiry",
    "Refund not credited",
    "Product quality issue",
    "Subscription cancellation",
    "Delivery delay"
]

print("Prompt template created successfully.")
print(f"Total scenarios : {len(SCENARIOS)}")

Prompt template created successfully.
Total scenarios : 7

In [ ]:
# Generate Synthetic Customer COnversations

import random

NUM_CONVERSATIONS = 5
records = []

for conversation_id in range(1, NUM_CONVERSATIONS +1):

    scenario = random.choice(SCENARIOS)
    print(f"Generating Conversation {conversation_id} | Scenario: {scenario}")

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=TRANSCRIPT_PROMPT.format(
            scenario=scenario
        )
    )

    transcript = response.output_text

    records.append(
        {
            "conversation_id": conversation_id,
            "scenario": scenario,
            "transcript": transcript
        }
    )

    print("="*80)
    print(transcript)
    print("="*80)


conversation_df = pd.DataFrame(records)
print("\n Dataset generated successfully.")

conversation_df.head()

Generating Conversation 1 | Scenario: Product quality issue
================================================================================
Customer: Hi, I recently bought one of your wireless headphones, and I'm having some problems with the sound quality.

Agent: Hello! I'm sorry to hear that. Can you tell me a bit more about the issue you're experiencing?

Customer: Yeah, sure. The sound keeps cutting out randomly, and sometimes there's this annoying static noise. It's really frustrating since I just got them last week.

Agent: That does sound frustrating. Just to clarify, is the issue happening with both earbuds or just one?

Customer: It's mostly happening in the right earbud, but occasionally in the left one too.

Agent: Thanks for that detail. Are you using them with any specific device, like a phone or a laptop?

Customer: Mostly with my phone, but I tried them with my laptop and noticed the same problem.

Agent: Got it. Have you tried resetting the headphones or updating their firmware? Sometimes that can help with connectivity issues.

Customer: I tried resetting them once, but I'm not sure about the firmware update. How would I do that?

Agent: I can guide you through it. You’ll want to connect the headphones to your phone and open our companion app. There’s an option to check for firmware updates right on the main screen.

Customer: Okay, I’ll give that a try after this call. What if that doesn't solve the problem?

Agent: If the update doesn’t fix it, we can arrange a replacement for you since it sounds like a defective unit. When did you purchase the headphones?

Customer: About six days ago, from your official website.

Agent: Perfect, you’re within the return window. If needed, I can send you a prepaid return label and make sure a new set is sent out as soon as we receive the faulty pair.

Customer: That would be great. I hope the update works, but I appreciate that option.

Agent: Absolutely. Feel free to contact us if you need any help during the update or if you decide to go ahead with the replacement.

Customer: Thanks for your help. I’ll try the firmware update now.

Agent: You're very welcome! Have a great day, and don’t hesitate to reach out if you need anything else.

Customer: Will do. Goodbye!

Agent: Goodbye!
================================================================================
Generating Conversation 2 | Scenario: Product Technical Support
================================================================================
Customer: Hi there, I recently bought your wireless headphones, and I'm having some trouble connecting them to my phone.

Agent: Hello! I'm sorry to hear you're having trouble. Let's see if we can get that sorted out. Can you tell me what model of phone you're using and which headphone model you have?

Customer: Sure, I have an iPhone 12, and the headphones are the XSound Pro model.

Agent: Great, thanks for that. When you try to connect, do the headphones appear in your Bluetooth list on the phone?

Customer: Actually, no. I’ve tried scanning for devices, but they don’t show up at all.

Agent: Got it. Let's make sure the headphones are in pairing mode. When you turn them on, do you see a blinking light, or any indication that they're ready to pair?

Customer: Hmm, the light is solid blue, not blinking. Does that mean they're not in pairing mode?

Agent: Exactly, a solid light usually means they're already connected to another device or not in pairing mode. Try turning them off and then press and hold the power button for about 5 seconds until the light starts flashing.

Customer: Okay, I did that now, and yes, the light is flashing blue and red.

Agent: Perfect. Now check your iPhone’s Bluetooth list again and see if "XSound Pro" appears.

Customer: Alright, I see it now. I’m selecting it.

Agent: Let me know if the connection goes through.

Customer: It connected! I can hear sound now.

Agent: Excellent! If you ever need to reconnect in the future, just make sure the headphones are in pairing mode and your phone’s Bluetooth is on. Anything else I can help you with today?

Customer: No, that was it. Thanks for your help!

Agent: You're very welcome. Have a great day and enjoy your music! If you need assistance later, don't hesitate to reach out. Goodbye!

Customer: Goodbye!
================================================================================
Generating Conversation 3 | Scenario: Product Inquiry
================================================================================
Customer: Hi, good afternoon. I was hoping you could help me with some questions about the SmartHome Air Purifier I’m considering buying?

Agent: Good afternoon! I’d be happy to help. What would you like to know about the SmartHome Air Purifier?

Customer: Well, I’m mostly concerned about its coverage area. I have a pretty big living room, around 500 square feet. Will this purifier be effective in a space that large?

Agent: That’s a great question. The SmartHome Air Purifier is designed to cover up to 400 square feet efficiently. For your living room size, it might not provide optimal performance on its own. Do you have any other rooms or areas where you’re planning to use it?

Customer: Yeah, I was thinking of using it mainly in the living room and sometimes in the connected dining area, which is about 200 square feet.

Agent: In that case, using it primarily in the living room might be a bit underpowered. However, moving it between the two areas could help maintain better air quality overall. Alternatively, we do have a larger model that covers up to 700 square feet, which might suit your needs better. Would you like information on that?

Customer: That sounds like a better fit. Could you tell me if the filters are replaceable and how often I’d need to change them?

Agent: Absolutely. The filters are replaceable, and we recommend changing them every 6 to 8 months, depending on usage and air quality conditions. The larger model uses the same type of filter, so maintenance is quite straightforward.

Customer: Got it. And is there a warranty on these units?

Agent: Yes, both models come with a one-year manufacturer’s warranty that covers defects and malfunctions. We also offer extended warranty options if you’re interested.

Customer: Thanks, that helps a lot. I think I want to go with the larger model then. How do I proceed with ordering?

Agent: You can order directly through our website or I can assist you with placing the order over the phone right now. Which would you prefer?

Customer: I think I’ll check out online, but I appreciate all your help!

Agent: You’re very welcome. If you have any more questions or need assistance during your purchase, feel free to reach out. Have a great day!

Customer: Thanks, you too! Goodbye.

Agent: Goodbye!
================================================================================
Generating Conversation 4 | Scenario: Billing Issue
================================================================================
Customer: Hi there, I hope you can help me. I noticed a charge on my credit card that I don’t recognize from your company.

Agent: Hello! I’m sorry to hear that there’s a charge you don’t recognize. Can you tell me the amount and the date of the transaction?

Customer: Sure, it’s for $49.99, and it was charged on the 15th of this month. I don’t remember making any purchase for that amount recently.

Agent: Thank you for that information. Can you please confirm the name on the account or the email address associated with your account so I can check the transaction details?

Customer: Yes, my email is john.doe@example.com.

Agent: Great, thank you. I’m pulling up your account now... Okay, I see a subscription renewal for a premium plan on the 15th. Does that sound familiar?

Customer: Oh, I guess I forgot about that subscription. I thought I had canceled it last month though.

Agent: I understand. Sometimes cancellations can take a couple of days to process. Let me check if the cancellation request was received or if it went through after the charge.

Customer: That would be helpful, thanks.

Agent: I see here that the cancellation request was made two days after the renewal date, so unfortunately, the charge for this billing cycle went through. However, I can offer a refund for this charge since you canceled shortly after.

Customer: That would be great, thank you. Will the service continue for the rest of the month or will it be canceled immediately?

Agent: The subscription will remain active until the end of the current billing period, but you won’t be charged again next month.

Customer: Perfect, I appreciate your help.

Agent: You’re very welcome! I’ll process the refund right now, and you should see it back on your credit card within 5 to 7 business days. Is there anything else I can assist you with today?

Customer: No, that’s everything. Thanks again for your prompt support.

Agent: It was my pleasure. Have a wonderful day and don’t hesitate to reach out if you need anything else!
================================================================================
Generating Conversation 5 | Scenario: Subscription cancellation
================================================================================
Customer: Hi there, I hope you can help me. I’d like to cancel my subscription, but I’m not sure how to go about it.

Agent: Hello! I’m sorry to hear you want to cancel. I can definitely assist with that. Could you please confirm your account email or username for verification?

Customer: Sure, my email is jane.doe@email.com.

Agent: Thank you, Jane. I’ve located your account. May I ask why you’re considering cancellation? Sometimes we might have solutions that better fit your needs.

Customer: Honestly, I just don’t use the service enough to justify the cost right now. Maybe I’ll come back later.

Agent: That makes sense, and I appreciate your honesty. To confirm, you want to cancel the subscription immediately and avoid future billing, correct?

Customer: Yes, exactly. And will I still be able to use the service until the current billing period ends?

Agent: Yes, you will have full access until the end of your current cycle, which is on the 15th of this month. After that, your subscription will not renew.

Customer: Great, that sounds good.

Agent: I’ve processed the cancellation for you. You will receive an email confirmation shortly. If you decide to return, please don’t hesitate to reach out or visit our website.

Customer: Thank you so much for your help and understanding.

Agent: You’re very welcome, Jane. Have a wonderful day, and take care!
================================================================================

 Dataset generated successfully.

In [8]:
# save dataset

conversation_df["audio_file_name"] = [
    f"call_{row.scenario}.wav"
    for index, row in conversation_df.iterrows()
]

conversation_df["audio_generated"] = False

csv_path = SAMPLE_DATA_DIR / "customer_conversations.csv"

conversation_df.to_csv(
    csv_path,
    index=False
)

print("Conversation dataset saved successfully.")
conversation_df

Conversation dataset saved successfully.

,conversation_id,scenario,transcript,audio_file_name,audio_generated
0,1,Product quality issue,"Customer: Hi, I recently bought one of your wi...",call_Product quality issue.wav,False
1,2,Product Technical Support,"Customer: Hi there, I recently bought your wir...",call_Product Technical Support.wav,False
2,3,Product Inquiry,"Customer: Hi, good afternoon. I was hoping you...",call_Product Inquiry.wav,False
3,4,Billing Issue,"Customer: Hi there, I hope you can help me. I ...",call_Billing Issue.wav,False
4,5,Subscription cancellation,"Customer: Hi there, I hope you can help me. I’...",call_Subscription cancellation.wav,False

In [9]:
# generate audio files
from pathlib import Path

voice = "alloy"

for index, row in conversation_df.iterrows():

    transcript = row["transcript"]
    audio_file = AUDIO_OUTPUT_DIR / row["audio_file_name"]

    print(f"Generating: {audio_file.name}")

    with client.audio.speech.with_streaming_response.create(
        model="gpt-4o-mini-tts",
        voice=voice,
        input=transcript,
        response_format="wav"
    ) as response:
        response.stream_to_file(audio_file)

    conversation_df.loc[index, "audio_generated"] = True

print("All audio files generated successfully.")

conversation_df

Generating: call_Product quality issue.wav
Generating: call_Product Technical Support.wav
Generating: call_Product Inquiry.wav
Generating: call_Billing Issue.wav
Generating: call_Subscription cancellation.wav
All audio files generated successfully.

,conversation_id,scenario,transcript,audio_file_name,audio_generated
0,1,Product quality issue,"Customer: Hi, I recently bought one of your wi...",call_Product quality issue.wav,True
1,2,Product Technical Support,"Customer: Hi there, I recently bought your wir...",call_Product Technical Support.wav,True
2,3,Product Inquiry,"Customer: Hi, good afternoon. I was hoping you...",call_Product Inquiry.wav,True
3,4,Billing Issue,"Customer: Hi there, I hope you can help me. I ...",call_Billing Issue.wav,True
4,5,Subscription cancellation,"Customer: Hi there, I hope you can help me. I’...",call_Subscription cancellation.wav,True